spring.application.name=jobportal

spring.datasource.url=jdbc:mysql://localhost:3306/jobportal_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=MySQL55$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Secret (Simple for project)
jwt.secret=9a67471b7f12e2c0576395349e5d481684c987826a7e089d7f12e2c057639534
jwt.expiration=86400000

# File Upload
file.upload-dir=./uploads/resumes
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
